Update index.js
When removing nodes, I was getting this error. Removing the call to masonry to remove it ended up solving my issue, but I'm not really sure right now.

```
TypeError: this.element.parentNode is null	
this.element.parentNode.removeChild( this.element );
```